### ISSUE TITLE
push support requires openssl

### ISSUE THREAD

**Issue by rillian** [Ptrskay3/axum-prometheus#42]
Hi! Thanks for publishing in a update on top of the new metrics-exporter-prometheus v0.13 release.

I notice that the new release [adds](https://github.com/metrics-rs/metrics/commit/d817f5c6f4909eeafbd9ff9ceadbf29302169bfa) an `openssl-sys` dependency through the `push-gateway` feature. This expands the code size a bit and more importantly complicates the build for us to no benefit I think, since we're using polling with external tls termination.

Would it be possible to move this under a corresponding feature in `axum-prometheus`, or if there's no way to configure gateway push through this crate just build `metrics-exporter-prometheus` without it?

**Comment by Ptrskay3** [comment]
Hi. I can make the that dependency feature optional, but it's kind of unfortunate to expose `metrics-exporter-prometheus`, but not with the default features.  If I understand correctly, eventually the root cause is in `metrics-exporter-prometheus`, requiring `openssl` support by default, and you're asking for something like this:

Cargo.toml
```toml
[dependencies]
# ...
metrics = "0.22.0"
metrics-exporter-prometheus = { version =  "0.13.0", optional =  true, default-features = false, features = ["http-listener"] }

[features]
default = ["prometheus"]
prometheus = ["metrics-exporter-prometheus"]
push-gateway = ["metrics-exporter-prometheus/push-gateway"]
```

Am I right?
